export const IpcChannels = {
  // Conversation
  CONVERSATION_LIST: 'conversation:list',
  CONVERSATION_GET: 'conversation:get',
  CONVERSATION_CREATE: 'conversation:create',
  CONVERSATION_UPDATE: 'conversation:update',
  CONVERSATION_DELETE: 'conversation:delete',
  CONVERSATION_DELETE_MANY: 'conversation:delete-many',
  // Message
  MESSAGE_LIST: 'message:list',
  MESSAGE_LIST_PAGINATED: 'message:list-paginated',
  MESSAGE_CREATE: 'message:create',
  MESSAGE_DELETE: 'message:delete',
  MESSAGE_UPDATE: 'message:update',
  MESSAGE_CLEAR: 'message:clear',
  MESSAGE_INSERT_DIVIDER: 'message:insert-divider',
  // Phrase
  PHRASE_LIST: 'phrase:list',
  PHRASE_CREATE: 'phrase:create',
  PHRASE_UPDATE: 'phrase:update',
  PHRASE_DELETE: 'phrase:delete',
  PHRASE_CLEAR: 'phrase:clear',
  // File
  FILE_OPEN_DIALOG: 'file:open-dialog',
  FILE_SAVE: 'file:save',
  ATTACHMENT_READ: 'attachment:read',
  // Settings
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_GET_ALL: 'settings:get-all',
  SETTINGS_SET_BATCH: 'settings:set-batch',
  SETTINGS_LANGUAGE_CHANGED: 'settings:language-changed',
  SETTINGS_CHANGED: 'settings:changed',
  // Tray (main → renderer push)
  TRAY_NEW_CONVERSATION: 'tray:new-conversation',
  TRAY_NAVIGATE_SETTINGS: 'tray:navigate-settings',
  // Provider
  PROVIDER_LIST: 'provider:list',
  PROVIDER_GET: 'provider:get',
  PROVIDER_CREATE: 'provider:create',
  PROVIDER_UPDATE: 'provider:update',
  PROVIDER_DELETE: 'provider:delete',
  PROVIDER_REORDER: 'provider:reorder',
  PROVIDER_TEST_CONNECTION: 'provider:test-connection',
  // Model
  MODEL_LIST: 'model:list',
  MODEL_CREATE: 'model:create',
  MODEL_UPDATE: 'model:update',
  MODEL_DELETE: 'model:delete',
  MODEL_DELETE_BY_PROVIDER: 'model:delete-by-provider',
  MODEL_REORDER: 'model:reorder',
  MODEL_FETCH_REMOTE: 'model:fetch-remote',
  // Model Definition (global capability library)
  MODEL_DEFINITION_LIST: 'model-definition:list',
  MODEL_DEFINITION_CREATE: 'model-definition:create',
  MODEL_DEFINITION_UPDATE: 'model-definition:update',
  MODEL_DEFINITION_DELETE: 'model-definition:delete',
  // Model Group (grouping rules for remote models)
  MODEL_GROUP_LIST: 'model-group:list',
  MODEL_GROUP_CREATE: 'model-group:create',
  MODEL_GROUP_UPDATE: 'model-group:update',
  MODEL_GROUP_DELETE: 'model-group:delete',
  // Assistant
  ASSISTANT_LIST: 'assistant:list',
  ASSISTANT_GET: 'assistant:get',
  ASSISTANT_CREATE: 'assistant:create',
  ASSISTANT_UPDATE: 'assistant:update',
  ASSISTANT_DELETE: 'assistant:delete',
  ASSISTANT_REORDER: 'assistant:reorder',
  // Assistant Template (library)
  ASSISTANT_TEMPLATE_LIST: 'assistant-template:list',
  ASSISTANT_TEMPLATE_GET: 'assistant-template:get',
  ASSISTANT_TEMPLATE_CREATE: 'assistant-template:create',
  ASSISTANT_TEMPLATE_UPDATE: 'assistant-template:update',
  ASSISTANT_TEMPLATE_DELETE: 'assistant-template:delete',
  ASSISTANT_TEMPLATE_REORDER: 'assistant-template:reorder',
  ASSISTANT_TEMPLATE_ADD_FROM_TEMPLATE: 'assistant-template:add-from-template',
  ASSISTANT_TEMPLATE_SAVE_AS_TEMPLATE: 'assistant-template:save-as-template',
  ASSISTANT_TEMPLATE_EXPORT_PACK: 'assistant-template:export-pack',
  ASSISTANT_TEMPLATE_IMPORT_PACK: 'assistant-template:import-pack',
  ASSISTANT_TEMPLATE_APPLY_IMPORT: 'assistant-template:apply-import',
  ASSISTANT_TEMPLATE_RESET_BUILTINS: 'assistant-template:reset-builtins',
  // Chat (streaming)
  CHAT_SEND_MESSAGE: 'chat:send-message',
  CHAT_STREAM_CHUNK: 'chat:stream-chunk',
  CHAT_STREAM_REASONING_CHUNK: 'chat:stream-reasoning-chunk',
  CHAT_STREAM_END: 'chat:stream-end',
  CHAT_STREAM_ERROR: 'chat:stream-error',
  CHAT_STOP_GENERATION: 'chat:stop-generation',
  CHAT_TITLE_UPDATED: 'chat:title-updated',
  // Translate (streaming)
  TRANSLATE_REQUEST: 'translate:request',
  TRANSLATE_CHUNK: 'translate:chunk',
  TRANSLATE_END: 'translate:end',
  TRANSLATE_ERROR: 'translate:error',
  TRANSLATE_STOP: 'translate:stop',
  // Translation History
  TRANSLATION_HISTORY_LIST: 'translation-history:list',
  TRANSLATION_HISTORY_CREATE: 'translation-history:create',
  TRANSLATION_HISTORY_CLEAR: 'translation-history:clear',
  // Window
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
  WINDOW_CLOSE_PROMPT: 'window:close-prompt',
  WINDOW_IS_MAXIMIZED: 'window:is-maximized',
  WINDOW_MAXIMIZED_CHANGE: 'window:maximized-change',
  WINDOW_TOGGLE_ALWAYS_ON_TOP: 'window:toggle-always-on-top',
  WINDOW_IS_ALWAYS_ON_TOP: 'window:is-always-on-top',
  WINDOW_ALWAYS_ON_TOP_CHANGE: 'window:always-on-top-change',
  // Zoom
  WINDOW_SET_ZOOM: 'window:set-zoom',
  WINDOW_GET_ZOOM: 'window:get-zoom',
  WINDOW_ZOOM_CHANGED: 'window:zoom-changed',
  // Fonts
  APP_GET_FONTS: 'app:get-fonts',
  // App
  APP_CLEAR_CHATS: 'app:clear-chats',
  APP_CLEAR_SETTINGS: 'app:clear-settings',
  APP_RESET: 'app:reset',
  APP_RELAUNCH: 'app:relaunch',
  APP_OPEN_PROJECT_PAGE: 'app:open-project-page',
  APP_OPEN_RELEASES_PAGE: 'app:open-releases-page',
  APP_GET_LATEST_RELEASE: 'app:get-latest-release',
  CLIPBOARD_WRITE_IMAGE: 'clipboard:write-image',
  // User
  USER_SAVE_AVATAR: 'user:save-avatar',
  USER_READ_AVATAR: 'user:read-avatar',
  // Quick Actions (CRUD)
  QUICK_ACTION_LIST: 'quick-action:list',
  QUICK_ACTION_CREATE: 'quick-action:create',
  QUICK_ACTION_UPDATE: 'quick-action:update',
  QUICK_ACTION_DELETE: 'quick-action:delete',
  QUICK_ACTION_REORDER: 'quick-action:reorder',
  // Quick Assistant (streaming)
  QUICK_ASSISTANT_REQUEST: 'quick-assistant:request',
  QUICK_ASSISTANT_CHUNK: 'quick-assistant:chunk',
  QUICK_ASSISTANT_END: 'quick-assistant:end',
  QUICK_ASSISTANT_ERROR: 'quick-assistant:error',
  QUICK_ASSISTANT_STOP: 'quick-assistant:stop',
  // Quick Assistant window
  QUICK_ASSISTANT_CLOSE: 'quick-assistant:close',
  QUICK_ASSISTANT_READY: 'quick-assistant:ready',
  QUICK_ASSISTANT_SET_PINNED: 'quick-assistant:set-pinned',
  QUICK_ASSISTANT_STATE_CHANGED: 'quick-assistant:state-changed',
  QUICK_ASSISTANT_UPDATE_SHORTCUT: 'quick-assistant:update-shortcut',
  QUICK_ASSISTANT_AUTO_EXECUTE: 'quick-assistant:auto-execute',
  QUICK_ASSISTANT_GET_PENDING_AUTO_EXECUTE: 'quick-assistant:get-pending-auto-execute',
  SUMMON_WINDOW_UPDATE_SHORTCUT: 'summon-window:update-shortcut',
  // Screenshot
  SCREENSHOT_DATA: 'screenshot:data',
  SCREENSHOT_COMPLETE: 'screenshot:complete',
  SCREENSHOT_CANCEL: 'screenshot:cancel',
  SCREENSHOT_UPDATE_SHORTCUT: 'screenshot:update-shortcut',
  // Selection Assistant — toolbar window
  SELECTION_TOOLBAR_READY: 'selection-toolbar:ready',
  SELECTION_TOOLBAR_DATA: 'selection-toolbar:data',
  SELECTION_TOOLBAR_ACTION: 'selection-toolbar:action',
  SELECTION_TOOLBAR_CLOSE: 'selection-toolbar:close',
  SELECTION_TOOLBAR_RESIZE: 'selection-toolbar:resize',
  // Selection Assistant — bubble window
  SELECTION_BUBBLE_READY: 'selection-bubble:ready',
  SELECTION_BUBBLE_DATA: 'selection-bubble:data',
  SELECTION_BUBBLE_CLOSE: 'selection-bubble:close',
  SELECTION_BUBBLE_SET_PINNED: 'selection-bubble:set-pinned',
  SELECTION_BUBBLE_SET_STREAMING: 'selection-bubble:set-streaming',
  // Selection Assistant — action CRUD
  SELECTION_ACTION_LIST: 'selection-action:list',
  SELECTION_ACTION_CREATE: 'selection-action:create',
  SELECTION_ACTION_UPDATE: 'selection-action:update',
  SELECTION_ACTION_DELETE: 'selection-action:delete',
  SELECTION_ACTION_REORDER: 'selection-action:reorder',
  // Selection Assistant — streaming AI
  SELECTION_REQUEST: 'selection:request',
  SELECTION_CHUNK: 'selection:chunk',
  SELECTION_END: 'selection:end',
  SELECTION_ERROR: 'selection:error',
  SELECTION_STOP: 'selection:stop',
  // Selection Assistant — toggle + shortcut + runtime config
  SELECTION_TOGGLE: 'selection:toggle',
  SELECTION_UPDATE_SHORTCUT: 'selection:update-shortcut',
  SELECTION_STATE_CHANGED: 'selection:state-changed',
  SELECTION_REFRESH_FILTER: 'selection:refresh-filter',
  // Backup
  BACKUP_EXPORT_TO_FILE: 'backup:export-to-file',
  BACKUP_IMPORT_FROM_FILE: 'backup:import-from-file',
  BACKUP_PEEK_FILE: 'backup:peek-file',
  BACKUP_PICK_FILE: 'backup:pick-file',
  BACKUP_GET_REMOTE_CONFIG: 'backup:get-remote-config',
  BACKUP_SET_REMOTE_CONFIG: 'backup:set-remote-config',
  BACKUP_CLEAR_REMOTE_CONFIG: 'backup:clear-remote-config',
  BACKUP_TEST_REMOTE: 'backup:test-remote',
  BACKUP_SYNC_NOW: 'backup:sync-now',
  BACKUP_SYNC_CANCEL: 'backup:sync-cancel',
  BACKUP_LIST_REMOTE: 'backup:list-remote',
  BACKUP_RESTORE_FROM_REMOTE: 'backup:restore-from-remote',
  BACKUP_GET_STATUS: 'backup:get-status',
  BACKUP_STATUS_CHANGED: 'backup:status-changed',
  BACKUP_PROGRESS: 'backup:progress',
  BACKUP_LIST_ROLLBACKS: 'backup:list-rollbacks',
  BACKUP_SET_REMOTE_ENABLED: 'backup:set-remote-enabled',
  // Auto Updater
  UPDATER_CHECK: 'updater:check',
  UPDATER_DOWNLOAD: 'updater:download',
  UPDATER_QUIT_AND_INSTALL: 'updater:quit-and-install',
  UPDATER_OPEN_RELEASE_PAGE: 'updater:open-release-page',
  UPDATER_GET_STATE: 'updater:get-state',
  UPDATER_STATE_CHANGED: 'updater:state-changed',
  // Web Search
  WEB_SEARCH_TEST_CONNECTION: 'web-search:test-connection',
  // Builtins (preset library: assistant templates / quick & selection actions)
  BUILTINS_GET_UPDATES_STATUS: 'builtins:get-updates-status',
  BUILTINS_APPLY_UPDATE: 'builtins:apply-update',
  // Catalog Sync (model definitions / groups from OpenRouter)
  CATALOG_SYNC_NOW: 'catalog:sync-now',
  CATALOG_GET_STATUS: 'catalog:get-status',
  CATALOG_STATUS_CHANGED: 'catalog:status-changed',
} as const
