export const IpcChannels = {
  // Conversation
  CONVERSATION_LIST: 'conversation:list',
  CONVERSATION_GET: 'conversation:get',
  CONVERSATION_CREATE: 'conversation:create',
  CONVERSATION_UPDATE: 'conversation:update',
  CONVERSATION_DELETE: 'conversation:delete',
  CONVERSATION_DELETE_MANY: 'conversation:delete-many',
  // Message
  MESSAGE_LIST: 'message:list',
  MESSAGE_LIST_PAGINATED: 'message:list-paginated',
  MESSAGE_CREATE: 'message:create',
  MESSAGE_DELETE: 'message:delete',
  MESSAGE_CLEAR: 'message:clear',
  MESSAGE_INSERT_DIVIDER: 'message:insert-divider',
  // Phrase
  PHRASE_LIST: 'phrase:list',
  PHRASE_CREATE: 'phrase:create',
  PHRASE_UPDATE: 'phrase:update',
  PHRASE_DELETE: 'phrase:delete',
  // File
  FILE_OPEN_DIALOG: 'file:open-dialog',
  ATTACHMENT_READ: 'attachment:read',
  // Settings
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_GET_ALL: 'settings:get-all',
  SETTINGS_SET_BATCH: 'settings:set-batch',
  // Provider
  PROVIDER_LIST: 'provider:list',
  PROVIDER_GET: 'provider:get',
  PROVIDER_CREATE: 'provider:create',
  PROVIDER_UPDATE: 'provider:update',
  PROVIDER_DELETE: 'provider:delete',
  PROVIDER_TEST_CONNECTION: 'provider:test-connection',
  // Model
  MODEL_LIST: 'model:list',
  MODEL_CREATE: 'model:create',
  MODEL_UPDATE: 'model:update',
  MODEL_DELETE: 'model:delete',
  // Assistant
  ASSISTANT_LIST: 'assistant:list',
  ASSISTANT_GET: 'assistant:get',
  ASSISTANT_CREATE: 'assistant:create',
  ASSISTANT_UPDATE: 'assistant:update',
  ASSISTANT_DELETE: 'assistant:delete',
  // Chat (streaming)
  CHAT_SEND_MESSAGE: 'chat:send-message',
  CHAT_STREAM_CHUNK: 'chat:stream-chunk',
  CHAT_STREAM_END: 'chat:stream-end',
  CHAT_STREAM_ERROR: 'chat:stream-error',
  CHAT_STOP_GENERATION: 'chat:stop-generation',
  CHAT_TITLE_UPDATED: 'chat:title-updated',
  // Translate (streaming)
  TRANSLATE_REQUEST: 'translate:request',
  TRANSLATE_CHUNK: 'translate:chunk',
  TRANSLATE_END: 'translate:end',
  TRANSLATE_ERROR: 'translate:error',
  TRANSLATE_STOP: 'translate:stop',
  // Translation History
  TRANSLATION_HISTORY_LIST: 'translation-history:list',
  TRANSLATION_HISTORY_CREATE: 'translation-history:create',
  TRANSLATION_HISTORY_CLEAR: 'translation-history:clear',
  // Window
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
  WINDOW_IS_MAXIMIZED: 'window:is-maximized',
  WINDOW_MAXIMIZED_CHANGE: 'window:maximized-change',
} as const
